import { SurveyCategory, SurveyQuestion } from '@/types/survey';

export const COLLABORATION_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'q37',
    questionNumber: 37,
    category: SurveyCategory.COLLABORATION,
    questionText: '팀원들의 감정과 상황을 잘 이해하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q38',
    questionNumber: 38,
    category: SurveyCategory.COLLABORATION,
    questionText: '혼자보다 함께 일할 때 더 좋은 결과가 나온다고 믿는다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q39',
    questionNumber: 39,
    category: SurveyCategory.COLLABORATION,
    questionText: '팀 내 갈등을 효과적으로 중재하고 해결하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q40',
    questionNumber: 40,
    category: SurveyCategory.COLLABORATION,
    questionText: '다른 사람의 성공을 진심으로 응원하고 지원한다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q41',
    questionNumber: 41,
    category: SurveyCategory.COLLABORATION,
    questionText: '다양한 배경과 의견을 가진 사람들과 잘 어울린다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q42',
    questionNumber: 42,
    category: SurveyCategory.COLLABORATION,
    questionText: '나의 필요보다 팀의 목표를 우선시하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q43',
    questionNumber: 43,
    category: SurveyCategory.COLLABORATION,
    questionText: '다른 사람의 아이디어에 귀 기울이고 그것을 발전시키는 것을 즐긴다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q44',
    questionNumber: 44,
    category: SurveyCategory.COLLABORATION,
    questionText: '협력보다 경쟁을 통해 더 좋은 결과를 만들 수 있다고 생각한다.',
    version: 1,
    isReverseScored: true,
    tier: 'basic',
  },
  {
    id: 'q45',
    questionNumber: 45,
    category: SurveyCategory.COLLABORATION,
    questionText: '팀원이 어려울 때 기꺼이 도움을 제공한다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q46',
    questionNumber: 46,
    category: SurveyCategory.COLLABORATION,
    questionText: '공동의 목표를 위해 내 방식을 조정하는 것이 어렵지 않다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q47',
    questionNumber: 47,
    category: SurveyCategory.COLLABORATION,
    questionText: '혼자 일하는 것이 팀으로 일하는 것보다 효율적이라고 느낀다.',
    version: 1,
    isReverseScored: true,
    tier: 'premium',
  },
  {
    id: 'q48',
    questionNumber: 48,
    category: SurveyCategory.COLLABORATION,
    questionText: '다른 사람의 관점에서 상황을 이해하려고 노력한다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
];
