import { SurveyCategory, SurveyQuestion } from '@/types/survey';

export const EXECUTION_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'q13',
    questionNumber: 13,
    category: SurveyCategory.EXECUTION,
    questionText: '한 번 맡은 일은 끝까지 완수하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q14',
    questionNumber: 14,
    category: SurveyCategory.EXECUTION,
    questionText: '목표를 세우고 그것을 달성하기 위한 계획을 구체적으로 수립한다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q15',
    questionNumber: 15,
    category: SurveyCategory.EXECUTION,
    questionText: '마감 기한을 철저히 지키는 것이 중요하다고 생각한다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q16',
    questionNumber: 16,
    category: SurveyCategory.EXECUTION,
    questionText: '세부적인 사항까지 꼼꼼하게 챙기는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q17',
    questionNumber: 17,
    category: SurveyCategory.EXECUTION,
    questionText: '업무를 처리할 때 체계적인 프로세스를 따른다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q18',
    questionNumber: 18,
    category: SurveyCategory.EXECUTION,
    questionText: '결과물의 완성도를 높이기 위해 충분한 시간을 투자한다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q19',
    questionNumber: 19,
    category: SurveyCategory.EXECUTION,
    questionText: '할 일 목록을 만들고 우선순위에 따라 처리하는 것이 어렵다.',
    version: 1,
    isReverseScored: true,
    tier: 'basic',
  },
  {
    id: 'q20',
    questionNumber: 20,
    category: SurveyCategory.EXECUTION,
    questionText: '어려운 상황에서도 포기하지 않고 방법을 찾아낸다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q21',
    questionNumber: 21,
    category: SurveyCategory.EXECUTION,
    questionText: '성과를 내기 위해 필요하다면 불편함을 감수할 수 있다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q22',
    questionNumber: 22,
    category: SurveyCategory.EXECUTION,
    questionText: '일을 시작하는 것보다 마무리하는 것이 더 어렵다고 느낀다.',
    version: 1,
    isReverseScored: true,
    tier: 'premium',
  },
  {
    id: 'q23',
    questionNumber: 23,
    category: SurveyCategory.EXECUTION,
    questionText: '높은 기준을 설정하고 그것을 충족시키기 위해 노력한다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q24',
    questionNumber: 24,
    category: SurveyCategory.EXECUTION,
    questionText: '업무의 효율성을 높이기 위한 방법을 지속적으로 탐색한다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
];
