import { SurveyCategory, SurveyQuestion } from '@/types/survey';

export const INFLUENCE_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'q25',
    questionNumber: 25,
    category: SurveyCategory.INFLUENCE,
    questionText: '다른 사람들이 내 의견을 따르는 경우가 많다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q26',
    questionNumber: 26,
    category: SurveyCategory.INFLUENCE,
    questionText: '내 생각을 설득력 있게 전달하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q27',
    questionNumber: 27,
    category: SurveyCategory.INFLUENCE,
    questionText: '사람들의 동기와 필요를 잘 파악하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q28',
    questionNumber: 28,
    category: SurveyCategory.INFLUENCE,
    questionText: '그룹에서 자연스럽게 리더 역할을 맡게 된다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q29',
    questionNumber: 29,
    category: SurveyCategory.INFLUENCE,
    questionText: '중요한 사안에 대해 내 입장을 명확히 표현한다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q30',
    questionNumber: 30,
    category: SurveyCategory.INFLUENCE,
    questionText: '내 행동이 주변 사람들에게 긍정적인 영향을 미친다고 느낀다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q31',
    questionNumber: 31,
    category: SurveyCategory.INFLUENCE,
    questionText: '사람들 앞에서 발표하거나 의견을 제시하는 것이 불편하다.',
    version: 1,
    isReverseScored: true,
    tier: 'basic',
  },
  {
    id: 'q32',
    questionNumber: 32,
    category: SurveyCategory.INFLUENCE,
    questionText: '협상이나 조율 상황에서 원하는 결과를 이끌어내는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q33',
    questionNumber: 33,
    category: SurveyCategory.INFLUENCE,
    questionText: '다른 사람들이 최선을 다하도록 동기를 부여하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q34',
    questionNumber: 34,
    category: SurveyCategory.INFLUENCE,
    questionText: '내 의견이 조직이나 팀의 방향에 영향을 미친다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q35',
    questionNumber: 35,
    category: SurveyCategory.INFLUENCE,
    questionText: '혼자 결정하는 것보다 다른 사람에게 판단을 맡기는 것이 편하다.',
    version: 1,
    isReverseScored: true,
    tier: 'premium',
  },
  {
    id: 'q36',
    questionNumber: 36,
    category: SurveyCategory.INFLUENCE,
    questionText: '내가 믿는 가치를 위해 목소리를 높이는 것을 두려워하지 않는다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
];
