import { SurveyCategory, SurveyQuestion } from '@/types/survey';

export const INNOVATION_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'q1',
    questionNumber: 1,
    category: SurveyCategory.INNOVATION,
    questionText: '새로운 아이디어를 떠올리는 것이 즐겁다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q2',
    questionNumber: 2,
    category: SurveyCategory.INNOVATION,
    questionText: '기존 방식에 의문을 제기하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q3',
    questionNumber: 3,
    category: SurveyCategory.INNOVATION,
    questionText: '문제를 해결할 때 여러 가지 창의적인 방법을 시도한다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q4',
    questionNumber: 4,
    category: SurveyCategory.INNOVATION,
    questionText: '남들이 보지 못하는 가능성을 발견하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q5',
    questionNumber: 5,
    category: SurveyCategory.INNOVATION,
    questionText: '새로운 기술이나 트렌드에 빠르게 관심을 갖는다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q6',
    questionNumber: 6,
    category: SurveyCategory.INNOVATION,
    questionText: '아이디어가 많아서 어떤 것부터 실행할지 고민될 때가 많다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q7',
    questionNumber: 7,
    category: SurveyCategory.INNOVATION,
    questionText: '나는 변화보다 안정된 환경을 선호한다.',
    version: 1,
    isReverseScored: true,
    tier: 'basic',
  },
  {
    id: 'q8',
    questionNumber: 8,
    category: SurveyCategory.INNOVATION,
    questionText: '실험적인 접근 방식을 시도할 때 두려움보다 기대감을 느낀다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q9',
    questionNumber: 9,
    category: SurveyCategory.INNOVATION,
    questionText: '다양한 분야에서 영감을 얻어 새로운 시각으로 문제를 본다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q10',
    questionNumber: 10,
    category: SurveyCategory.INNOVATION,
    questionText: '주어진 조건 안에서만 생각하는 것이 더 편하다.',
    version: 1,
    isReverseScored: true,
    tier: 'premium',
  },
  {
    id: 'q11',
    questionNumber: 11,
    category: SurveyCategory.INNOVATION,
    questionText: '미래의 가능성을 상상하고 그에 맞게 행동하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q12',
    questionNumber: 12,
    category: SurveyCategory.INNOVATION,
    questionText: '낯선 것을 접했을 때 불편함보다 호기심을 더 많이 느낀다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
];
