import { SurveyCategory, SurveyQuestion } from '@/types/survey';

export const RESILIENCE_QUESTIONS: SurveyQuestion[] = [
  {
    id: 'q49',
    questionNumber: 49,
    category: SurveyCategory.RESILIENCE,
    questionText: '실패나 역경을 겪어도 빠르게 회복하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q50',
    questionNumber: 50,
    category: SurveyCategory.RESILIENCE,
    questionText: '예상치 못한 변화에도 침착하게 대응하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q51',
    questionNumber: 51,
    category: SurveyCategory.RESILIENCE,
    questionText: '스트레스 상황에서도 명확한 판단력을 유지한다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q52',
    questionNumber: 52,
    category: SurveyCategory.RESILIENCE,
    questionText: '어려운 상황을 성장의 기회로 바라보는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q53',
    questionNumber: 53,
    category: SurveyCategory.RESILIENCE,
    questionText: '비판이나 부정적인 피드백을 받아도 과도하게 위축되지 않는다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q54',
    questionNumber: 54,
    category: SurveyCategory.RESILIENCE,
    questionText: '장기적인 목표를 위해 단기적인 불편함을 견딜 수 있다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q55',
    questionNumber: 55,
    category: SurveyCategory.RESILIENCE,
    questionText: '일이 잘 풀리지 않을 때 쉽게 포기하고 싶어진다.',
    version: 1,
    isReverseScored: true,
    tier: 'basic',
  },
  {
    id: 'q56',
    questionNumber: 56,
    category: SurveyCategory.RESILIENCE,
    questionText: '불확실한 상황에서도 낙관적인 태도를 유지한다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q57',
    questionNumber: 57,
    category: SurveyCategory.RESILIENCE,
    questionText: '과거의 실수에 오래 집착하기보다 앞으로 나아가는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q58',
    questionNumber: 58,
    category: SurveyCategory.RESILIENCE,
    questionText: '환경이 바뀌면 쉽게 적응하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q59',
    questionNumber: 59,
    category: SurveyCategory.RESILIENCE,
    questionText: '압박이 심한 상황에서 오히려 더 집중력이 높아진다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q60',
    questionNumber: 60,
    category: SurveyCategory.RESILIENCE,
    questionText: '도전적인 목표가 있을 때 더 큰 동기를 느낀다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
];
