import { IS_TOSS } from './design-tokens';
import type { CSSProperties } from 'react';

/** SajuProfileSection 스타일 */
export const sajuProfileStyles = IS_TOSS ? {
  sectionLabel: 'text-xs font-semibold tracking-widest text-tds-blue-500 uppercase',
  sectionTitle: 'text-t3 font-bold text-tds-grey-900',
  sectionSubtitle: 'text-tds-grey-400 font-normal text-lg',
  emptyPillarCard: 'flex flex-col items-center justify-center rounded-2xl border border-tds-grey-200 bg-tds-grey-50 min-h-[160px]',
  emptyPillarLabel: 'text-xs text-tds-grey-400',
  emptyPillarSub: 'text-xs text-tds-grey-300 mt-1',
  card: 'rounded-2xl border border-tds-grey-200 bg-white p-6',
  cardTitle: 'text-sm font-semibold text-tds-grey-500 mb-4',
  dayMasterCardTitle: 'text-sm font-semibold text-tds-grey-500',
  dayMasterName: 'text-xl font-bold',
  dayMasterSub: 'text-xs text-tds-grey-400',
  dayMasterDesc: 'text-sm text-tds-grey-600 leading-relaxed',
  cardFill: '',
} : {
  sectionLabel: 'text-xs font-semibold tracking-widest text-primary/70 uppercase',
  sectionTitle: 'text-2xl font-bold text-foreground',
  sectionSubtitle: 'text-muted-foreground/50 font-normal text-lg',
  emptyPillarCard: 'flex flex-col items-center justify-center rounded-2xl border border-border bg-card min-h-[160px]',
  emptyPillarLabel: 'text-xs text-muted-foreground/40',
  emptyPillarSub: 'text-xs text-muted-foreground/30 mt-1',
  card: 'rounded-2xl border border-border p-6',
  cardTitle: 'text-sm font-semibold text-muted-foreground/80 mb-4',
  dayMasterCardTitle: 'text-sm font-semibold text-muted-foreground/80',
  dayMasterName: 'text-xl font-bold',
  dayMasterSub: 'text-xs text-muted-foreground/50',
  dayMasterDesc: 'text-sm text-muted-foreground leading-relaxed',
  cardFill: 'bg-card',
} as const;

/** CrossAnalysisSection 스타일 */
export const crossAnalysisStyles = IS_TOSS ? {
  sectionLabel: 'text-xs font-semibold tracking-widest text-tds-blue-400 uppercase',
  sectionTitle: 'text-t3 font-bold text-tds-grey-900',
  sectionSubtitle: 'text-tds-grey-400 font-normal text-lg',
  sectionDesc: 'text-sm text-tds-grey-500',
  card: 'rounded-2xl border border-tds-grey-200 bg-white p-6',
  cardTitle: 'text-sm font-semibold text-tds-grey-500 mb-4',
  matrixDesc: 'text-[11px] text-tds-grey-400',
  matrixEmpty: 'text-xs text-tds-grey-300',
  matrixItem: 'text-xs text-tds-grey-500 flex items-center gap-2',
  insightTitle: 'text-sm font-semibold text-tds-grey-500',
  insightText: 'text-sm text-tds-grey-600 leading-relaxed pl-5',
  cardFill: '',
} : {
  sectionLabel: 'text-xs font-semibold tracking-widest text-primary/70 uppercase',
  sectionTitle: 'text-2xl font-bold text-foreground',
  sectionSubtitle: 'text-muted-foreground/50 font-normal text-lg',
  sectionDesc: 'text-sm text-muted-foreground/70',
  card: 'rounded-2xl border border-border p-6',
  cardTitle: 'text-sm font-semibold text-muted-foreground/80 mb-4',
  matrixDesc: 'text-[11px] text-muted-foreground/50',
  matrixEmpty: 'text-xs text-muted-foreground/40',
  matrixItem: 'text-xs text-muted-foreground/80 flex items-center gap-2',
  insightTitle: 'text-sm font-semibold text-muted-foreground/80',
  insightText: 'text-sm text-muted-foreground/85 leading-relaxed pl-5',
  cardFill: 'bg-card',
} as const;

/** PsaProfileSection 스타일 */
export const psaProfileStyles = IS_TOSS ? {
  sectionLabel: 'text-xs font-semibold tracking-widest text-tds-blue-400 uppercase',
  sectionTitle: 'text-t3 font-bold text-tds-grey-900',
  sectionSubtitle: 'text-tds-grey-400 font-normal text-lg',
  card: 'rounded-2xl border border-tds-grey-200 bg-white p-6',
  cardTitle: 'text-sm font-semibold text-tds-grey-500 mb-2',
  personaCard: 'rounded-2xl border border-tds-grey-200 bg-white p-6 space-y-4',
  personaCardTitle: 'text-sm font-semibold text-tds-grey-500',
  personaTitle: 'text-2xl font-bold text-tds-blue-600',
  personaTagline: 'text-sm text-tds-grey-500 mt-1 italic',
  strengthsSummary: 'text-sm text-tds-grey-600 leading-relaxed',
  scoreCard: 'rounded-2xl border border-tds-grey-200 bg-white p-6 space-y-4',
  scoreCardTitle: 'text-sm font-semibold text-tds-grey-500',
  scoreLabel: 'text-sm text-tds-grey-600 w-20 flex-shrink-0',
  scoreBar: 'flex-1 h-2 rounded-full bg-tds-grey-100 overflow-hidden',
  cardFill: '' as string,
  personaBgStyle: undefined as CSSProperties | undefined,
  radarGridStroke: 'rgba(0,0,0,0.08)',
  radarTickFill: '#6B7280',
} : {
  sectionLabel: 'text-xs font-semibold tracking-widest text-primary/70 uppercase',
  sectionTitle: 'text-2xl font-bold text-foreground',
  sectionSubtitle: 'text-muted-foreground/50 font-normal text-lg',
  card: 'rounded-2xl border border-border p-6',
  cardTitle: 'text-sm font-semibold text-muted-foreground/80 mb-2',
  personaCard: 'rounded-2xl border border-primary/20 p-6 space-y-4',
  personaCardTitle: 'text-sm font-semibold text-muted-foreground/80',
  personaTitle: 'text-2xl font-bold text-primary',
  personaTagline: 'text-sm text-muted-foreground/70 mt-1 italic',
  strengthsSummary: 'text-sm text-muted-foreground leading-relaxed',
  scoreCard: 'rounded-2xl border border-border p-6 space-y-4',
  scoreCardTitle: 'text-sm font-semibold text-muted-foreground/80',
  scoreLabel: 'text-sm text-muted-foreground w-20 flex-shrink-0',
  scoreBar: 'flex-1 h-2 rounded-full bg-secondary overflow-hidden',
  cardFill: 'bg-card' as string,
  personaBgStyle: {
    background: "linear-gradient(160deg, rgba(6,182,212,0.08) 0%, rgba(6,182,212,0.02) 100%)",
  } as CSSProperties | undefined,
  radarGridStroke: 'hsl(var(--border))',
  radarTickFill: 'hsl(var(--muted-foreground))',
};

/** GrowthGuideSection 스타일 */
export const growthGuideStyles = IS_TOSS ? {
  sectionLabel: 'text-xs font-semibold tracking-widest text-tds-green-500 uppercase',
  sectionTitle: 'text-t3 font-bold text-tds-grey-900',
  summaryCard: 'rounded-2xl border border-tds-grey-200 bg-white p-6',
  summaryTitle: 'text-sm font-semibold text-tds-green-600 mb-3',
  summaryText: 'text-sm text-tds-grey-600 leading-relaxed',
  focusTitle: 'text-sm font-semibold text-tds-grey-500',
  focusCard: 'rounded-xl border border-tds-grey-200 bg-white p-4 space-y-2',
  focusIndex: 'w-6 h-6 rounded-full bg-tds-green-100 text-tds-green-600 text-xs flex items-center justify-center font-bold flex-shrink-0',
  focusArea: 'text-sm font-semibold text-tds-grey-800',
  focusAdvice: 'text-sm text-tds-grey-500 leading-relaxed pl-8',
  practiceCard: 'rounded-xl border border-tds-grey-200 bg-white p-5',
  practiceTitle: 'text-sm font-semibold text-tds-grey-500 mb-2',
  practiceText: 'text-sm text-tds-grey-600 leading-relaxed',
  tipsTitle: 'text-sm font-semibold text-tds-grey-500',
  tipCard: 'rounded-xl border border-tds-grey-200 bg-white p-4 space-y-1.5',
  tipTitle: 'text-sm font-semibold text-tds-blue-600',
  tipText: 'text-sm text-tds-grey-500 leading-relaxed',
  brandingTitle: 'text-sm font-semibold text-tds-grey-500',
  brandingCard: 'rounded-xl border border-tds-grey-200 bg-white p-4 space-y-1.5',
  brandingLabel: 'text-xs text-tds-grey-400 font-medium',
  brandingText: 'text-sm text-tds-grey-700 leading-relaxed',
  pitchCard: 'rounded-xl border border-tds-grey-200 bg-white p-4 space-y-1.5',
  pitchLabel: 'text-xs text-tds-grey-400 font-medium',
  pitchText: 'text-sm text-tds-grey-700 leading-relaxed',
  hashtag: 'text-xs px-3 py-1.5 rounded-full border border-tds-grey-200 text-tds-grey-500 font-medium bg-tds-grey-50',
  cardFill: '' as string,
  summaryBgStyle: undefined as CSSProperties | undefined,
  tipBgStyle: undefined as CSSProperties | undefined,
  pitchBgStyle: undefined as CSSProperties | undefined,
  hashtagBgStyle: undefined as CSSProperties | undefined,
} : {
  sectionLabel: 'text-xs font-semibold tracking-widest text-muted-foreground uppercase',
  sectionTitle: 'text-2xl font-bold text-foreground',
  summaryCard: 'rounded-2xl border border-border p-6',
  summaryTitle: 'text-sm font-semibold text-primary mb-3',
  summaryText: 'text-sm text-muted-foreground leading-relaxed',
  focusTitle: 'text-sm font-semibold text-muted-foreground/80',
  focusCard: 'rounded-xl border border-border p-4 space-y-2',
  focusIndex: 'w-6 h-6 rounded-full bg-primary/20 text-primary text-xs flex items-center justify-center font-bold flex-shrink-0',
  focusArea: 'text-sm font-semibold text-foreground/80',
  focusAdvice: 'text-sm text-muted-foreground/70 leading-relaxed pl-8',
  practiceCard: 'rounded-xl border border-border p-5',
  practiceTitle: 'text-sm font-semibold text-muted-foreground/80 mb-2',
  practiceText: 'text-sm text-muted-foreground leading-relaxed',
  tipsTitle: 'text-sm font-semibold text-muted-foreground/80',
  tipCard: 'rounded-xl border border-primary/15 p-4 space-y-1.5',
  tipTitle: 'text-sm font-semibold text-primary',
  tipText: 'text-sm text-muted-foreground/80 leading-relaxed',
  brandingTitle: 'text-sm font-semibold text-muted-foreground/80',
  brandingCard: 'rounded-xl border border-border p-4 space-y-1.5',
  brandingLabel: 'text-xs text-muted-foreground/50 font-medium',
  brandingText: 'text-sm text-foreground/80 leading-relaxed',
  pitchCard: 'rounded-xl border border-primary/15 p-4 space-y-1.5',
  pitchLabel: 'text-xs text-primary/70 font-medium',
  pitchText: 'text-sm text-muted-foreground leading-relaxed',
  hashtag: 'text-xs px-3 py-1.5 rounded-full border border-border text-muted-foreground/70 font-medium',
  cardFill: 'bg-card' as string,
  summaryBgStyle: {
    background: "linear-gradient(160deg, rgba(34,197,94,0.07) 0%, rgba(34,197,94,0.02) 100%)",
  } as CSSProperties | undefined,
  tipBgStyle: { background: "rgba(6,182,212,0.05)" } as CSSProperties | undefined,
  pitchBgStyle: { background: "rgba(49,130,246,0.05)" } as CSSProperties | undefined,
  hashtagBgStyle: { background: "rgba(255,255,255,0.04)" } as CSSProperties | undefined,
};

/** BirthInfoPage 스타일 */
export const birthInfoStyles = IS_TOSS ? {
  page: 'min-h-screen bg-white',
  container: 'px-6 py-6 pb-[calc(100px+env(safe-area-inset-bottom))]',
  title: 'text-t3 font-bold text-tds-grey-900',
  subtitle: 'text-st8 text-tds-grey-700',
  card: 'bg-white border border-tds-grey-200 rounded-xl p-6',
  stepActive: 'w-8 h-8 rounded-full bg-tds-blue-500 text-white flex items-center justify-center text-t7 font-bold',
  stepInactive: 'w-8 h-8 rounded-full border-2 border-tds-grey-300 text-tds-grey-500 flex items-center justify-center text-t7',
  stepLine: 'h-0.5 flex-1 bg-tds-grey-200',
  stepLineActive: 'h-0.5 flex-1 bg-tds-blue-500',
  stepLabel: 'text-st11 text-tds-blue-500 font-medium',
  stepLabelInactive: 'text-st11 text-tds-grey-500',
  error: 'text-st10 text-tds-red-500',
  mainBg: 'bg-white',
  mainPx: 'px-6',
} : {
  page: 'min-h-screen bg-background',
  container: 'px-4 py-8 max-w-2xl mx-auto pb-32',
  title: 'text-2xl font-bold text-foreground',
  subtitle: 'text-sm text-muted-foreground',
  card: 'bg-card border border-border rounded-2xl p-6',
  stepActive: 'w-8 h-8 rounded-full bg-primary text-white flex items-center justify-center text-xs font-bold',
  stepInactive: 'w-8 h-8 rounded-full border-2 border-border text-muted-foreground/50 flex items-center justify-center text-xs',
  stepLine: 'h-0.5 flex-1 bg-border',
  stepLineActive: 'h-0.5 flex-1 bg-primary',
  stepLabel: 'text-xs text-primary font-medium',
  stepLabelInactive: 'text-xs text-muted-foreground/50',
  error: 'text-sm text-destructive',
  mainBg: 'bg-background',
  mainPx: 'px-4',
} as const;

/** PrivacyPolicyPage 스타일 */
export const privacyPolicyStyles = IS_TOSS ? {
  page: 'min-h-screen bg-white',
  container: 'px-6 py-8',
  title: 'text-t2 font-bold text-tds-grey-900',
  body: 'text-st8 text-tds-grey-700 leading-relaxed',
  heading: 'text-t5 font-semibold text-tds-grey-900',
} : {
  page: 'min-h-screen bg-background',
  container: 'px-4 py-12 max-w-2xl mx-auto',
  title: 'text-3xl font-bold text-foreground',
  body: 'text-sm text-muted-foreground leading-relaxed',
  heading: 'text-lg font-semibold text-foreground',
} as const;

/** 서베이 페이지 토큰 */
export const surveyTokens = IS_TOSS ? {
  page: 'min-h-screen bg-white',
  header: 'sticky top-0 z-30 bg-white border-b border-tds-grey-200',
  headerTitle: 'text-t5 font-semibold text-tds-grey-900',
  questionCard: 'bg-tds-grey-50 rounded-xl border border-tds-grey-200 p-5',
  questionNumber: 'bg-tds-blue-50 text-tds-blue-500 rounded-full px-2.5 py-0.5 text-st11 font-medium',
  questionText: 'text-t5 font-semibold text-tds-grey-900',
  questionCategory: 'text-st11 text-tds-grey-500',
  likertSelected: 'bg-tds-blue-500 text-white border-tds-blue-500 rounded-xl',
  likertUnselected: 'bg-tds-grey-100 border border-tds-grey-300 text-tds-grey-700 rounded-xl hover:bg-tds-grey-200',
  likertLabel: 'text-st11 text-tds-grey-500',
  bottomNav: 'fixed bottom-0 left-0 right-0 bg-white z-40',
  bottomGradient: 'h-9 bg-gradient-to-b from-transparent to-white pointer-events-none -mt-9',
  dotActive: 'w-2.5 h-2.5 rounded-full bg-tds-blue-500',
  dotCompleted: 'w-2 h-2 rounded-full bg-tds-blue-200',
  dotPending: 'w-2 h-2 rounded-full bg-tds-grey-300',
  container: 'px-6 py-4 pb-[calc(120px+env(safe-area-inset-bottom))]',
  bodyText: 'text-st8 text-tds-grey-700',
  caption: 'text-st11 text-tds-grey-500',
} : {
  page: 'min-h-screen bg-background',
  header: 'sticky top-0 z-30 bg-background/80 backdrop-blur-md border-b border-border',
  headerTitle: 'text-lg font-semibold text-foreground',
  questionCard: 'bg-card rounded-xl p-5 border border-border',
  questionNumber: 'bg-primary/10 text-primary rounded-full px-2.5 py-0.5 text-xs font-medium',
  questionText: 'text-lg font-semibold text-card-foreground',
  questionCategory: 'text-xs text-muted-foreground',
  likertSelected: 'bg-primary text-primary-foreground border-transparent rounded-[14px]',
  likertUnselected: 'bg-secondary border border-border text-secondary-foreground rounded-[14px] hover:bg-secondary/80',
  likertLabel: 'text-xs text-muted-foreground',
  bottomNav: 'fixed bottom-0 left-0 right-0 bg-background border-t border-border z-40',
  bottomGradient: '',
  dotActive: 'w-2.5 h-2.5 rounded-full bg-primary',
  dotCompleted: 'w-2 h-2 rounded-full bg-primary/50',
  dotPending: 'w-2 h-2 rounded-full bg-muted',
  container: 'px-4 py-4 pb-32',
  bodyText: 'text-sm text-muted-foreground',
  caption: 'text-xs text-muted-foreground/50',
} as const;

/** 결과 페이지 토큰 */
export const resultTokens = IS_TOSS ? {
  page: 'min-h-screen bg-white',
  container: 'px-6 py-6',
  title: 'text-t2 font-bold text-tds-grey-900',
  subtitle: 'text-st8 text-tds-grey-700',
  sectionTitle: 'text-t3 font-bold text-tds-grey-900',
  bodyText: 'text-st8 text-tds-grey-700',
  caption: 'text-st11 text-tds-grey-500',
  card: 'bg-white border border-tds-grey-200 rounded-xl p-5',
  divider: 'border-t border-tds-grey-200 my-8',
  shareButton: 'bg-tds-blue-500 text-white rounded-[14px] px-6 py-3 font-semibold text-t6',
} : {
  page: 'min-h-screen bg-background text-foreground',
  container: 'px-4 py-8 max-w-2xl mx-auto',
  title: 'text-3xl font-bold text-foreground',
  subtitle: 'text-sm text-muted-foreground',
  sectionTitle: 'text-2xl font-bold text-foreground',
  bodyText: 'text-sm text-muted-foreground',
  caption: 'text-xs text-muted-foreground/50',
  card: 'bg-card border border-border rounded-2xl p-5',
  divider: 'border-t border-border my-8',
  shareButton: 'bg-primary text-primary-foreground rounded-[14px] px-6 py-3 font-bold',
} as const;
