import { SurveyCategory, SurveyQuestion } from '@/types/survey';

export const SURVEY_QUESTIONS: SurveyQuestion[] = [
  // ==========================================
  // Innovation (혁신 사고) - 12 questions
  // Basic: q1-q5, q7(R) | Premium: q6, q8-q12
  // ==========================================
  {
    id: 'q1',
    questionNumber: 1,
    category: SurveyCategory.INNOVATION,
    questionText: '새로운 아이디어를 떠올리는 것이 즐겁다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q2',
    questionNumber: 2,
    category: SurveyCategory.INNOVATION,
    questionText: '기존 방식에 의문을 제기하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q3',
    questionNumber: 3,
    category: SurveyCategory.INNOVATION,
    questionText: '문제를 해결할 때 여러 가지 창의적인 방법을 시도한다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q4',
    questionNumber: 4,
    category: SurveyCategory.INNOVATION,
    questionText: '남들이 보지 못하는 가능성을 발견하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q5',
    questionNumber: 5,
    category: SurveyCategory.INNOVATION,
    questionText: '새로운 기술이나 트렌드에 빠르게 관심을 갖는다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q6',
    questionNumber: 6,
    category: SurveyCategory.INNOVATION,
    questionText: '아이디어가 많아서 어떤 것부터 실행할지 고민될 때가 많다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q7',
    questionNumber: 7,
    category: SurveyCategory.INNOVATION,
    questionText: '나는 변화보다 안정된 환경을 선호한다.',
    version: 1,
    isReverseScored: true,
    tier: 'basic',
  },
  {
    id: 'q8',
    questionNumber: 8,
    category: SurveyCategory.INNOVATION,
    questionText: '실험적인 접근 방식을 시도할 때 두려움보다 기대감을 느낀다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q9',
    questionNumber: 9,
    category: SurveyCategory.INNOVATION,
    questionText: '다양한 분야에서 영감을 얻어 새로운 시각으로 문제를 본다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q10',
    questionNumber: 10,
    category: SurveyCategory.INNOVATION,
    questionText: '주어진 조건 안에서만 생각하는 것이 더 편하다.',
    version: 1,
    isReverseScored: true,
    tier: 'premium',
  },
  {
    id: 'q11',
    questionNumber: 11,
    category: SurveyCategory.INNOVATION,
    questionText: '미래의 가능성을 상상하고 그에 맞게 행동하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q12',
    questionNumber: 12,
    category: SurveyCategory.INNOVATION,
    questionText: '낯선 것을 접했을 때 불편함보다 호기심을 더 많이 느낀다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },

  // ==========================================
  // Execution (철저 실행) - 12 questions
  // Basic: q13-q17, q19(R) | Premium: q18, q20-q24
  // ==========================================
  {
    id: 'q13',
    questionNumber: 13,
    category: SurveyCategory.EXECUTION,
    questionText: '한 번 맡은 일은 끝까지 완수하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q14',
    questionNumber: 14,
    category: SurveyCategory.EXECUTION,
    questionText: '목표를 세우고 그것을 달성하기 위한 계획을 구체적으로 수립한다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q15',
    questionNumber: 15,
    category: SurveyCategory.EXECUTION,
    questionText: '마감 기한을 철저히 지키는 것이 중요하다고 생각한다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q16',
    questionNumber: 16,
    category: SurveyCategory.EXECUTION,
    questionText: '세부적인 사항까지 꼼꼼하게 챙기는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q17',
    questionNumber: 17,
    category: SurveyCategory.EXECUTION,
    questionText: '업무를 처리할 때 체계적인 프로세스를 따른다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q18',
    questionNumber: 18,
    category: SurveyCategory.EXECUTION,
    questionText: '결과물의 완성도를 높이기 위해 충분한 시간을 투자한다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q19',
    questionNumber: 19,
    category: SurveyCategory.EXECUTION,
    questionText: '할 일 목록을 만들고 우선순위에 따라 처리하는 것이 어렵다.',
    version: 1,
    isReverseScored: true,
    tier: 'basic',
  },
  {
    id: 'q20',
    questionNumber: 20,
    category: SurveyCategory.EXECUTION,
    questionText: '어려운 상황에서도 포기하지 않고 방법을 찾아낸다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q21',
    questionNumber: 21,
    category: SurveyCategory.EXECUTION,
    questionText: '성과를 내기 위해 필요하다면 불편함을 감수할 수 있다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q22',
    questionNumber: 22,
    category: SurveyCategory.EXECUTION,
    questionText: '일을 시작하는 것보다 마무리하는 것이 더 어렵다고 느낀다.',
    version: 1,
    isReverseScored: true,
    tier: 'premium',
  },
  {
    id: 'q23',
    questionNumber: 23,
    category: SurveyCategory.EXECUTION,
    questionText: '높은 기준을 설정하고 그것을 충족시키기 위해 노력한다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q24',
    questionNumber: 24,
    category: SurveyCategory.EXECUTION,
    questionText: '업무의 효율성을 높이기 위한 방법을 지속적으로 탐색한다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },

  // ==========================================
  // Influence (대인 영향) - 12 questions
  // Basic: q25-q29, q31(R) | Premium: q30, q32-q36
  // ==========================================
  {
    id: 'q25',
    questionNumber: 25,
    category: SurveyCategory.INFLUENCE,
    questionText: '다른 사람들이 내 의견을 따르는 경우가 많다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q26',
    questionNumber: 26,
    category: SurveyCategory.INFLUENCE,
    questionText: '내 생각을 설득력 있게 전달하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q27',
    questionNumber: 27,
    category: SurveyCategory.INFLUENCE,
    questionText: '사람들의 동기와 필요를 잘 파악하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q28',
    questionNumber: 28,
    category: SurveyCategory.INFLUENCE,
    questionText: '그룹에서 자연스럽게 리더 역할을 맡게 된다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q29',
    questionNumber: 29,
    category: SurveyCategory.INFLUENCE,
    questionText: '중요한 사안에 대해 내 입장을 명확히 표현한다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q30',
    questionNumber: 30,
    category: SurveyCategory.INFLUENCE,
    questionText: '내 행동이 주변 사람들에게 긍정적인 영향을 미친다고 느낀다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q31',
    questionNumber: 31,
    category: SurveyCategory.INFLUENCE,
    questionText: '사람들 앞에서 발표하거나 의견을 제시하는 것이 불편하다.',
    version: 1,
    isReverseScored: true,
    tier: 'basic',
  },
  {
    id: 'q32',
    questionNumber: 32,
    category: SurveyCategory.INFLUENCE,
    questionText: '협상이나 조율 상황에서 원하는 결과를 이끌어내는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q33',
    questionNumber: 33,
    category: SurveyCategory.INFLUENCE,
    questionText: '다른 사람들이 최선을 다하도록 동기를 부여하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q34',
    questionNumber: 34,
    category: SurveyCategory.INFLUENCE,
    questionText: '내 의견이 조직이나 팀의 방향에 영향을 미친다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q35',
    questionNumber: 35,
    category: SurveyCategory.INFLUENCE,
    questionText: '혼자 결정하는 것보다 다른 사람에게 판단을 맡기는 것이 편하다.',
    version: 1,
    isReverseScored: true,
    tier: 'premium',
  },
  {
    id: 'q36',
    questionNumber: 36,
    category: SurveyCategory.INFLUENCE,
    questionText: '내가 믿는 가치를 위해 목소리를 높이는 것을 두려워하지 않는다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },

  // ==========================================
  // Collaboration (협업 공감) - 12 questions
  // Basic: q37-q41, q44(R) | Premium: q42-q43, q45-q48
  // ==========================================
  {
    id: 'q37',
    questionNumber: 37,
    category: SurveyCategory.COLLABORATION,
    questionText: '팀원들의 감정과 상황을 잘 이해하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q38',
    questionNumber: 38,
    category: SurveyCategory.COLLABORATION,
    questionText: '혼자보다 함께 일할 때 더 좋은 결과가 나온다고 믿는다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q39',
    questionNumber: 39,
    category: SurveyCategory.COLLABORATION,
    questionText: '팀 내 갈등을 효과적으로 중재하고 해결하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q40',
    questionNumber: 40,
    category: SurveyCategory.COLLABORATION,
    questionText: '다른 사람의 성공을 진심으로 응원하고 지원한다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q41',
    questionNumber: 41,
    category: SurveyCategory.COLLABORATION,
    questionText: '다양한 배경과 의견을 가진 사람들과 잘 어울린다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q42',
    questionNumber: 42,
    category: SurveyCategory.COLLABORATION,
    questionText: '나의 필요보다 팀의 목표를 우선시하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q43',
    questionNumber: 43,
    category: SurveyCategory.COLLABORATION,
    questionText: '다른 사람의 아이디어에 귀 기울이고 그것을 발전시키는 것을 즐긴다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q44',
    questionNumber: 44,
    category: SurveyCategory.COLLABORATION,
    questionText: '협력보다 경쟁을 통해 더 좋은 결과를 만들 수 있다고 생각한다.',
    version: 1,
    isReverseScored: true,
    tier: 'basic',
  },
  {
    id: 'q45',
    questionNumber: 45,
    category: SurveyCategory.COLLABORATION,
    questionText: '팀원이 어려울 때 기꺼이 도움을 제공한다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q46',
    questionNumber: 46,
    category: SurveyCategory.COLLABORATION,
    questionText: '공동의 목표를 위해 내 방식을 조정하는 것이 어렵지 않다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q47',
    questionNumber: 47,
    category: SurveyCategory.COLLABORATION,
    questionText: '혼자 일하는 것이 팀으로 일하는 것보다 효율적이라고 느낀다.',
    version: 1,
    isReverseScored: true,
    tier: 'premium',
  },
  {
    id: 'q48',
    questionNumber: 48,
    category: SurveyCategory.COLLABORATION,
    questionText: '다른 사람의 관점에서 상황을 이해하려고 노력한다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },

  // ==========================================
  // Resilience (상황 회복) - 12 questions
  // Basic: q49-q53, q55(R) | Premium: q54, q56-q60
  // ==========================================
  {
    id: 'q49',
    questionNumber: 49,
    category: SurveyCategory.RESILIENCE,
    questionText: '실패나 역경을 겪어도 빠르게 회복하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q50',
    questionNumber: 50,
    category: SurveyCategory.RESILIENCE,
    questionText: '예상치 못한 변화에도 침착하게 대응하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q51',
    questionNumber: 51,
    category: SurveyCategory.RESILIENCE,
    questionText: '스트레스 상황에서도 명확한 판단력을 유지한다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q52',
    questionNumber: 52,
    category: SurveyCategory.RESILIENCE,
    questionText: '어려운 상황을 성장의 기회로 바라보는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q53',
    questionNumber: 53,
    category: SurveyCategory.RESILIENCE,
    questionText: '비판이나 부정적인 피드백을 받아도 과도하게 위축되지 않는다.',
    version: 1,
    isReverseScored: false,
    tier: 'basic',
  },
  {
    id: 'q54',
    questionNumber: 54,
    category: SurveyCategory.RESILIENCE,
    questionText: '장기적인 목표를 위해 단기적인 불편함을 견딜 수 있다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q55',
    questionNumber: 55,
    category: SurveyCategory.RESILIENCE,
    questionText: '일이 잘 풀리지 않을 때 쉽게 포기하고 싶어진다.',
    version: 1,
    isReverseScored: true,
    tier: 'basic',
  },
  {
    id: 'q56',
    questionNumber: 56,
    category: SurveyCategory.RESILIENCE,
    questionText: '불확실한 상황에서도 낙관적인 태도를 유지한다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q57',
    questionNumber: 57,
    category: SurveyCategory.RESILIENCE,
    questionText: '과거의 실수에 오래 집착하기보다 앞으로 나아가는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q58',
    questionNumber: 58,
    category: SurveyCategory.RESILIENCE,
    questionText: '환경이 바뀌면 쉽게 적응하는 편이다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q59',
    questionNumber: 59,
    category: SurveyCategory.RESILIENCE,
    questionText: '압박이 심한 상황에서 오히려 더 집중력이 높아진다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
  {
    id: 'q60',
    questionNumber: 60,
    category: SurveyCategory.RESILIENCE,
    questionText: '도전적인 목표가 있을 때 더 큰 동기를 느낀다.',
    version: 1,
    isReverseScored: false,
    tier: 'premium',
  },
];

/** @deprecated 하위 호환용 — 새 코드에서는 BASIC_QUESTIONS_PER_PAGE 사용 */
export const QUESTIONS_PER_PAGE = 6;
/** @deprecated 하위 호환용 — 새 코드에서는 BASIC_TOTAL_PAGES 사용 */
export const TOTAL_PAGES = 10;

// ==========================================
// Tier-based exports (Basic 30 / Premium 30)
// ==========================================
export const BASIC_QUESTIONS: SurveyQuestion[] = SURVEY_QUESTIONS.filter(q => q.tier === 'basic');
export const PREMIUM_QUESTIONS: SurveyQuestion[] = SURVEY_QUESTIONS.filter(q => q.tier === 'premium');
export const BASIC_QUESTIONS_PER_PAGE = 6;
export const BASIC_TOTAL_PAGES = 5;
